### ISSUE TITLE
[BUG] Exception in callback SyncBase during claim

### ISSUE THREAD

**Issue by Tiippex** [srhinos/primelooter#12]
Hey, thanks for keeping the looter up to date :)

During the claim process, the looter throws an error:
```
2022-03-24 22:53:56 [WARNING] Could not claim Geschenk des Kobolds from World of Warships: Legends by Wargaming Group, Ltd (in-game loot),
2022-03-24 22:53:59 [ERROR] Exception in callback SyncBase._sync.<locals>.callback(<Task finishe...630'}, ...}}}>) at /usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py:104,
handle: <Handle SyncBase._sync.<locals>.callback(<Task finishe...630'}, ...}}}>) at /usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py:104>,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run,
    self._context.run(self._callback, *self._args),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 105, in callback,
    g_self.switch(),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 122, in <lambda>,
    lambda params: self._on_response(,
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 397, in _on_response,
    page.emit(Page.Events.Response, response),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 113, in emit,
    handled = self._call_handlers(event, args, kwargs),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 96, in _call_handlers,
    self._emit_run(f, args, kwargs),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_asyncio.py", line 42, in _emit_run,
    self.emit('error', exc),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 116, in emit,
    self._emit_handle_potential_error(event, args[0] if args else None),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 86, in _emit_handle_potential_error,
    raise error,
  File "/usr/local/lib/python3.8/dist-packages/pyee/_asyncio.py", line 40, in _emit_run,
    coro = f(*args, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 121, in listener,
    self._fulfill(event_data),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 99, in _fulfill,
    self._cleanup(),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 96, in _cleanup,
    listener[0].remove_listener(listener[1], listener[2]),
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 297, in remove_listener,
    super().remove_listener(event, f),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 152, in remove_listener,
    self._remove_listener(event, f),
  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 147, in _remove_listener,
    self._events[event].pop(f),
KeyError: <function WaitHelper.reject_on_event.<locals>.listener at 0x7f96c6d5be50>,
2022-03-24 22:54:03 [WARNING] Could not claim Premium-Vorratspaket Nr.1 from PUBG: Battlegrounds by Krafton (in-game loot)
```

I'm running the docker image with portainer on a Debian server.

**Comment by srhinos** [comment]
While there were a few css selector change, this error is prolly from needing to update playwright. I updated and the issue was gone but given you're running in docker and assuming you freshly built and it still occurred (which it hasn't for me), its gonna be difficult to debug until https://github.com/srhinos/primelooter/issues/8 gets tackled since the abstraction layer between async and sync fucks up the logs and digging into playwright docs is toxic since Microsoft :(
    
Reopen if its still occuring and I'll dig into it at some point but for sure poke if its hindering functionality which I can't tell if it is or not.
