### ISSUE TITLE
[BUG] Playwright library KeyError

### ISSUE THREAD

**Issue by srhinos** [srhinos/primelooter#15]
❓**Describe the bug**
Occassionally, a playwright library error will bubble up but it doesn't appear to cause any issues with the actual functionality of the script.

📝**To Reproduce**
Unsure how to repro, haven't been able to consistently repro :(

🔎**Expected behavior**
No playwright errors should occur during regular operation

⚙️**Environment Details(please complete the following information):**
 - OS: Windows WSL2.0
 - Python Version: 3.8
 - Version: 1.3.3

💬**Additional context**
- Occurs during running of `claim_external` though nothing in the traceback signifies this.
- I have a gut feeling will be easier to fix once #8 gets completed but also unsure and the resolution of #8 is a massive task, essentially a codebase rewrite.

Traceback:
```
2022-03-27 20:05:54 [ERROR] Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe...58183e7e0'}}}>) at /home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:84
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe...58183e7e0'}}}>) at /home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:84>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 84, in <lambda>
    task.add_done_callback(lambda _: g_self.switch())
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", line 122, in <lambda>
    lambda params: self._on_response(
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", line 397, in _on_response
    page.emit(Page.Events.Response, response)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_wait_helper.py", line 121, in listener
    self._fulfill(event_data)
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_wait_helper.py", line 99, in _fulfill
    self._cleanup()
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_wait_helper.py", line 96, in _cleanup
    listener[0].remove_listener(listener[1], listener[2])
  File "/home/rhino/.local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 297, in remove_listener
    super().remove_listener(event, f)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 152, in remove_listener
    self._remove_listener(event, f)
  File "/home/rhino/.local/lib/python3.8/site-packages/pyee/_base.py", line 147, in _remove_listener
    self._events[event].pop(f)
KeyError: <function WaitHelper.reject_on_event.<locals>.listener at 0x7f102d4c1430>
```

**Comment by dlooto** [comment]
I also had this problem, when running claim_external.
