### ISSUE TITLE
Script errors out and keeps repeating itself

### ISSUE THREAD

**Issue by bencmeyer** [srhinos/primelooter#24]
I am running the docker container within unRaid

Thank you for maintaining this project.
Recently, the container has been causing the docker service to lock up.
Looking through logs, it appears the primelooter script continually errors out and loops continually until I kill it.

This is the long error
```
today at 12:12:28 AM  2022-06-29 00:12:28 [ERROR] Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe...b9761cdd8'}}}>) at /usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py:85
today at 12:12:28 AM  handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe...b9761cdd8'}}}>) at /usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py:85>
today at 12:12:28 AM  Traceback (most recent call last):
today at 12:12:28 AM  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
today at 12:12:28 AM    self._context.run(self._callback, *self._args)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 85, in <lambda>
today at 12:12:28 AM    task.add_done_callback(lambda _: g_self.switch())
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 122, in <lambda>
today at 12:12:28 AM    lambda params: self._on_response(
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 402, in _on_response
today at 12:12:28 AM    page.emit(Page.Events.Response, response)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 113, in emit
today at 12:12:28 AM    handled = self._call_handlers(event, args, kwargs)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 96, in _call_handlers
today at 12:12:28 AM    self._emit_run(f, args, kwargs)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_asyncio.py", line 42, in _emit_run
today at 12:12:28 AM    self.emit('error', exc)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 116, in emit
today at 12:12:28 AM    self._emit_handle_potential_error(event, args[0] if args else None)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
today at 12:12:28 AM    raise error
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_asyncio.py", line 40, in _emit_run
today at 12:12:28 AM    coro = f(*args, **kwargs)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 119, in listener
today at 12:12:28 AM    self._fulfill(event_data)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 97, in _fulfill
today at 12:12:28 AM    self._cleanup()
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_wait_helper.py", line 94, in _cleanup
today at 12:12:28 AM    listener[0].remove_listener(listener[1], listener[2])
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 303, in remove_listener
today at 12:12:28 AM    super().remove_listener(event, f)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 152, in remove_listener
today at 12:12:28 AM    self._remove_listener(event, f)
today at 12:12:28 AM  File "/usr/local/lib/python3.8/dist-packages/pyee/_base.py", line 147, in _remove_listener
today at 12:12:28 AM    self._events[event].pop(f)
today at 12:12:28 AM  KeyError: <function WaitHelper.reject_on_event.<locals>.listener at 0x1466c8ab3dc0>
```
Followed by this, and then it restarts over again.
```
today at 12:13:04 AM  Timeout 30000.0ms exceeded while waiting for event "response"
today at 12:13:04 AM  2022-06-29 00:13:04 [ERROR] local variable 'game_name' referenced before assignment
```

Full log attached
[PrimeLooter-2022-06-29T05-21-45.log](https://github.com/srhinos/primelooter/files/9007478/PrimeLooter-2022-06-29T05-21-45.log)

**Comment by srhinos** [comment]
This was fixed by https://github.com/srhinos/primelooter/commit/839e492c8e9c9cf56d1d4d97443f9227df729d44

Pull the most recent image and you should be good to go!

**Comment by bencmeyer** [comment]
I am already running 1.3.5

**Comment by srhinos** [comment]
the exact set of errors is indicative of not running 1.3.5, I highly suggest you double check the version you have locally is the most recent.

**Comment by bencmeyer** [comment]
Deleted image and redownloaded.
Verified primelooter.py has the addition. Same error.
